version: '3'

services:
  data:
    build: .
    command: /bin/true
    environment:
      - RSYNC_REPO=app1
      - RSYNC_FILE=backup.tgz
      - RSYNC_SERVER=rsyncd.server.lan
      - RSYNC_USER=rsync-user
      - RSYNC_PASSWORD=rsync-password
      - MYSQL_SERVER=mysql.server.lan
      - MYSQL_BDD=bdd1
      - MYSQL_USER=mysql-user
      - MYSQL_PASSWORD=mysql-password
      - DOCKER_DATA_DIRECTORY=/data
      - DOCKER_DATA_USER=user
      - DOCKER_FILE_TEST_EXISTS=/data/file
    volumes:
      - data:/data

volumes:
  data:
    driver: local
